### ISSUE TITLE
Ghostbin is down.

### ISSUE THREAD

**Issue by LucidGrassHopper** [DHowett/spectre#84]
I cannot access ghostbin.com, Google Chrome (desktop) responds with the message "This site can’t be reached ghostbin.com took too long to respond."

I confirmed it is not just me by using these websites:
http://www.isitdownrightnow.com/ghostbin.com.html
https://down.com/?q=https://www.ghostbin.com
https://downforeveryoneorjustme.com/ghostbin.com

**Comment by andrew867** [comment]
Yes it is down, I heard it might be a DDoS

**Comment by LucidGrassHopper** [comment]
Maybe someone could convince the owner of Ghostbin to use [Cloudflare](https://www.cloudflare.com/ddos/) to defend against DDoS attacks? I believe that Ghostbin would fall into the category of "Personal Website", which means Cloudflare is free.

It's really disheartening to see Ghostbin go down so frequently, I've used it occasionally for the past two years and it always seems to work for a few days and then go down for a week.

**Comment by regic** [comment]
It is down for me, too. @DHowett

**Comment by AnastasiaDunbar** [comment]
I've also got some pastes in Ghostbin.

**Comment by regic** [comment]
It is up and running again! :heart: Thanks a lot, @DHowett !

**Comment by bionichuman** [comment]
You guys know if this is still open-source? Trying to host my own...

**Comment by bionichuman** [comment]
The code on this page doesnt seem to work.

**Comment by Hekter** [comment]
@bionichuman Some of the dependencies are out of date so Ghostbin will not build from scratch. Someone built a Docker file with Ghostbin that you might have better luck with here: https://hub.docker.com/r/platzhalter/ghostbin/ or this other project here: https://github.com/dexafree/ghostbin. Note that Ghostbin requires to be at the top level domain, and will not accept being put on a subdomain.

**Comment by bionichuman** [comment]
@Hekter Does this have all the features ghost bin currently has?

**Comment by bionichuman** [comment]
@Hekter I read it and it says it wont have all the current features. Did you set it up using the docker file? Did it work for you?

**Comment by Hekter** [comment]
@bionichuman I got the dexafree one up and running a while ago, but I didn't do extensive testing. As for missing features, the only note I see is that Dexafree notes that for all the features to work it needs to be run on a Linux system. Ghostbin doesn't use a database to store pastes and their metadata, rather it uses extended file system attributes, which does not work on Windows.

**Comment by bionichuman** [comment]
@Hekter Do you remember what features it is missing? I got it running on linux but am not actually sure how to run the program.. I did the command like it said but dont know what to do now....

**Comment by bionichuman** [comment]
@Hekter If you could help me out and have discord join my server here....

https://discord.gg/dDu3XT3

Anyone else is welcome too. I will be attempting to get this to work...

**Comment by bionichuman** [comment]
@Hekter Do you know if the creator will ever publish the code that is currently running right now? He hasnt responded to my email or tweets....

**Comment by Hekter** [comment]
@bionichuman I'm honestly not 100% sure what code is running on the production server vs what is in this repo. I doubt they'll ever be reconciled as I know he was in the middle of a rewrite to use a database instead of extended file attributes, a cleaner system (like a main.go file that isn't 1800 lines long), etc. but I know he hasn't had the time/energy to really devote to it lately.

As for the "missing features" Dexafree points that out in his readme:
This is due to a difference in the internal Filesystem Docker for Linux uses: The FS driver used on Docker for macOS and Docker for Windows does not support the use of xattrs (extended attributes: saving metadata for a file in the filesystem), and Ghostbin relies on those attributes for saving the paste properties, such as the language, the encryption password and the expiration (if any of those is set).

It might be worthwhile to read up more on Docker to give you some more context, but if it's running, you probably need to re-route the port 80 traffic to whatever port the Ghostbin docker is explosing. Both of the images expose port 8619. How do to the traffic re-routing is going to depend on what webserver software you are using. Platzhalter's page goes over both Nginx and Apache. https://hub.docker.com/r/platzhalter/ghostbin/

**Comment by DHowett** [comment]
The code that is currently running right now is bit-for-bit identical with the code in this repository's `v1-stable` branch. The deployment pipeline is [here](https://gitlab.howett.net/Ghostbin/spectre/pipelines/154) and the CI configuration that leads _to_ it being deployed is [here](https://gitlab.howett.net/Ghostbin/spectre/blob/v1-stable/.gitlab-ci.yml).

If you click into the jobs on the pipeline page, you can see the build and deployment phases and their full logs. In addition, the **(artifacts)[https://gitlab.howett.net/Ghostbin/spectre/-/jobs/345/artifacts/browse]** for the latest _legacy build_ contains the actual binary drop that's deployed to ghostbin.com.

**Comment by DHowett** [comment]
Incidentally, that CI configuration and [the builder's dockerfile](https://gitlab.howett.net/Ghostbin/builder/blob/master/Dockerfile) show you _precisely_ what's required to build ghostbin for yourself.

**Comment by bionichuman** [comment]
@DHowett Im confused what all that meant.... 

So the CI config and builder's dock file is what is on ghostbin.com right now?

**Comment by bionichuman** [comment]
@Hekter How do I run the files on my domain? I got it setup and working on my vps. 

I got to my ip:8080 and it works.

I want to get it on my domain though... What file is the file being shown on the page when I go to it? Is there an idex somewhere?

**Comment by DHowett** [comment]
@bionichuman What I'm saying is "all the code here is the code on ghostbin.com". I think you need some assistance that we can't provide in the Ghostbin issue tracker, however -- we don't have the resources to adequately help you.

Since Ghostbin is no longer down, I'm going to close this issue. If you want to continue the discussion around self-hosting, please move it to #85.
